import * as XLSX from "xlsx";

/**
 * Export data to CSV file
 */
export function exportToCSV(data: any[], filename: string) {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csv = XLSX.utils.sheet_to_csv(worksheet);
  
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Export data to Excel file
 */
export function exportToExcel(data: any[], filename: string, sheetName: string = "Sheet1") {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  
  XLSX.writeFile(workbook, `${filename}.xlsx`);
}

/**
 * Export multiple sheets to Excel file
 */
export function exportMultiSheetExcel(
  sheets: Array<{ name: string; data: any[] }>,
  filename: string
) {
  const workbook = XLSX.utils.book_new();
  
  sheets.forEach((sheet) => {
    const worksheet = XLSX.utils.json_to_sheet(sheet.data);
    XLSX.utils.book_append_sheet(workbook, worksheet, sheet.name);
  });
  
  XLSX.writeFile(workbook, `${filename}.xlsx`);
}

/**
 * Format booking data for export
 */
export function formatBookingsForExport(bookings: any[]) {
  return bookings.map((booking) => ({
    "Booking ID": booking.id,
    "Office Name": booking.officeName || "N/A",
    "Service": booking.serviceDescription,
    "Status": booking.status,
    "Scheduled Date": booking.scheduledDate
      ? new Date(booking.scheduledDate).toLocaleDateString()
      : "Not scheduled",
    "Scheduled Time": booking.scheduledTime || "N/A",
    "Duration (min)": booking.duration,
    "Price (OMR)": booking.price || "0",
    "Payment Status": booking.paymentStatus || "unpaid",
    "Created At": new Date(booking.createdAt).toLocaleString(),
  }));
}

/**
 * Format document statistics for export
 */
export function formatDocumentsForExport(documents: any[]) {
  return documents.map((doc) => ({
    "Document ID": doc.id,
    "Template Name": doc.templateName,
    "Category": doc.category,
    "Generated By": doc.userName || "Unknown",
    "Generated At": new Date(doc.createdAt).toLocaleString(),
    "File Size": doc.fileSize ? `${(doc.fileSize / 1024).toFixed(2)} KB` : "N/A",
  }));
}

/**
 * Format office performance for export
 */
export function formatOfficesForExport(offices: any[]) {
  return offices.map((office) => ({
    "Office ID": office.id,
    "Office Name": office.officeName,
    "Region": office.region,
    "Status": office.status,
    "Total Bookings": office.totalBookings || 0,
    "Completed Bookings": office.completedBookings || 0,
    "Average Rating": office.averageRating ? office.averageRating.toFixed(2) : "N/A",
    "Total Reviews": office.totalReviews || 0,
    "Created At": new Date(office.createdAt).toLocaleDateString(),
  }));
}
