import { jsPDF } from "jspdf";
import type { DocumentTemplate } from "../drizzle/schema";

/**
 * PDF Generator for SmartPro Document Templates
 * Generates professional PDFs from templates with user-filled data
 */

interface GeneratePDFOptions {
  template: DocumentTemplate;
  filledData: Record<string, any>;
  language?: "en" | "ar";
}

/**
 * Generate a PDF document from a template and filled data
 */
export async function generatePDF(options: GeneratePDFOptions): Promise<Buffer> {
  const { template, filledData, language = "en" } = options;

  // Create new PDF document
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const isArabic = language === "ar";
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  // Set up fonts and styling
  doc.setFont("helvetica");
  
  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  const title = isArabic && template.templateNameAr ? template.templateNameAr : template.templateName;
  doc.text(title, pageWidth / 2, margin, { align: "center" });

  // Add horizontal line
  doc.setLineWidth(0.5);
  doc.line(margin, margin + 10, pageWidth - margin, margin + 10);

  // Document date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const dateStr = new Date().toLocaleDateString(isArabic ? "ar-OM" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Date: ${dateStr}`, margin, margin + 18);

  // Content area
  let yPosition = margin + 30;

  // Process template content and replace variables
  let content = template.templateContent;
  
  // Replace all variables with filled data
  template.variables.forEach((variable) => {
    const value = filledData[variable.name] || "";
    const placeholder = `{{${variable.name}}}`;
    content = content.replace(new RegExp(placeholder, "g"), String(value));
  });

  // Remove HTML tags for plain text rendering
  content = content.replace(/<[^>]*>/g, "");
  
  // Split content into lines and render
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  
  const lines = doc.splitTextToSize(content, contentWidth);
  
  lines.forEach((line: string) => {
    if (yPosition > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
    doc.text(line, margin, yPosition);
    yPosition += 7;
  });

  // Add field values section
  yPosition += 10;
  if (yPosition > pageHeight - margin - 50) {
    doc.addPage();
    yPosition = margin;
  }

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Document Details:", margin, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  template.variables.forEach((variable) => {
    if (yPosition > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }

    const label = isArabic && variable.labelAr ? variable.labelAr : variable.label;
    const value = filledData[variable.name] || "N/A";
    
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, yPosition);
    doc.setFont("helvetica", "normal");
    doc.text(String(value), margin + 60, yPosition);
    yPosition += 7;
  });

  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text("Generated by SmartPro Platform", pageWidth / 2, footerY, { align: "center" });
  doc.text("www.smartpro.om", pageWidth / 2, footerY + 4, { align: "center" });

  // Convert to buffer
  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
  return pdfBuffer;
}

/**
 * Generate employment contract PDF (specialized template)
 */
export async function generateEmploymentContract(filledData: Record<string, any>): Promise<Buffer> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("EMPLOYMENT CONTRACT", pageWidth / 2, margin, { align: "center" });

  doc.setLineWidth(0.5);
  doc.line(margin, margin + 5, pageWidth - margin, margin + 5);

  let y = margin + 15;

  // Contract content
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const content = `
This Employment Contract is entered into on ${filledData.contractDate || "___________"} between:

EMPLOYER:
Company Name: ${filledData.companyName || "___________"}
Commercial Registration: ${filledData.companyRegistration || "___________"}
Address: ${filledData.companyAddress || "___________"}

EMPLOYEE:
Full Name: ${filledData.employeeName || "___________"}
Civil ID: ${filledData.employeeCivilId || "___________"}
Nationality: ${filledData.employeeNationality || "___________"}
Address: ${filledData.employeeAddress || "___________"}

TERMS AND CONDITIONS:

1. POSITION AND DUTIES
The Employee is hired for the position of ${filledData.jobTitle || "___________"} and shall perform duties as assigned by the Employer.

2. COMMENCEMENT DATE
Employment shall commence on ${filledData.startDate || "___________"}.

3. PROBATION PERIOD
The Employee shall be on probation for ${filledData.probationPeriod || "3"} months.

4. SALARY AND BENEFITS
Basic Salary: ${filledData.basicSalary || "___________"} OMR per month
Housing Allowance: ${filledData.housingAllowance || "0"} OMR per month
Transport Allowance: ${filledData.transportAllowance || "0"} OMR per month

5. WORKING HOURS
The Employee shall work ${filledData.workingHours || "48"} hours per week.

6. ANNUAL LEAVE
The Employee is entitled to ${filledData.annualLeave || "30"} days of paid annual leave per year.

7. TERMINATION
Either party may terminate this contract with ${filledData.noticePeriod || "30"} days written notice.

This contract is governed by the laws of the Sultanate of Oman.
`;

  const lines = doc.splitTextToSize(content, pageWidth - 2 * margin);
  
  lines.forEach((line: string) => {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 6;
  });

  // Signature section
  y += 10;
  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = margin;
  }

  doc.setFont("helvetica", "bold");
  doc.text("EMPLOYER SIGNATURE:", margin, y);
  doc.text("EMPLOYEE SIGNATURE:", pageWidth / 2 + 10, y);
  
  y += 15;
  doc.line(margin, y, margin + 60, y);
  doc.line(pageWidth / 2 + 10, y, pageWidth - margin, y);

  y += 5;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Date: ___________", margin, y);
  doc.text("Date: ___________", pageWidth / 2 + 10, y);

  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
  return pdfBuffer;
}

/**
 * Generate NOC (No Objection Certificate) PDF
 */
export async function generateNOC(filledData: Record<string, any>): Promise<Buffer> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("NO OBJECTION CERTIFICATE", pageWidth / 2, margin, { align: "center" });

  doc.setLineWidth(0.5);
  doc.line(margin, margin + 5, pageWidth - margin, margin + 5);

  let y = margin + 20;

  // Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${filledData.issueDate || new Date().toLocaleDateString()}`, pageWidth - margin - 40, y);

  y += 15;

  // Content
  doc.setFontSize(11);
  const content = `
To Whom It May Concern,

This is to certify that ${filledData.companyName || "___________"}, Commercial Registration No. ${filledData.companyRegistration || "___________"}, has NO OBJECTION to:

Employee Name: ${filledData.employeeName || "___________"}
Civil ID: ${filledData.employeeCivilId || "___________"}
Passport No: ${filledData.passportNumber || "___________"}
Nationality: ${filledData.nationality || "___________"}
Position: ${filledData.position || "___________"}

For the purpose of: ${filledData.purpose || "___________"}

${filledData.additionalNotes || ""}

This certificate is issued upon the employee's request and for official use only.
`;

  const lines = doc.splitTextToSize(content, pageWidth - 2 * margin);
  
  lines.forEach((line: string) => {
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 7;
  });

  // Signature section
  y += 20;
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Signatory", margin, y);
  
  y += 10;
  doc.line(margin, y, margin + 60, y);
  
  y += 5;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Company Stamp", margin, y);

  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
  return pdfBuffer;
}
