import React, { createContext, useContext, useState, useEffect, type ReactNode } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.sanadOffices": "Sanad Offices",
    "nav.documentTemplates": "Document Templates",
    "nav.myBookings": "My Bookings",
    "nav.myOffices": "My Offices",
    "nav.ownerDashboard": "Owner Dashboard",
    "nav.chatInbox": "Chat Inbox",
    "nav.chatAnalytics": "Chat Analytics",
    "nav.cannedResponses": "Canned Responses",
    "nav.staffManagement": "Staff Management",
    "nav.staffPerformance": "Staff Performance",
    "nav.followUpSettings": "Follow-up Settings",
    "nav.loyaltyRewards": "Loyalty Rewards",
    "nav.referFriends": "Refer Friends",
    "nav.analytics": "Analytics",
    "nav.userProfile": "User Profile",
    "nav.contentTranslation": "Content Translation",
    "nav.notificationPreferences": "Notification Preferences",
    "nav.adminDashboard": "Admin Dashboard",
    "nav.adminAnalytics": "Admin Analytics",
    "nav.marketplace": "Browse Marketplace",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.myServiceRequests": "My Service Requests",
    "nav.browseMarketplace": "Browse Marketplace",
    "nav.officeAnalytics": "Office Analytics",
    "nav.userManagement": "User Management",
    "nav.officeVerification": "Office Verification",
    "nav.translationRequests": "Translation Requests",
    "nav.translationAnalytics": "Translation Analytics",
    "nav.translationQuality": "Translation Quality",
    "nav.reviewQueue": "Review Queue",
    "nav.batchProcessing": "Batch Processing",
    "nav.translatorTraining": "Translator Training",
    
    // Home page
    "home.hero.title": "Everything You Need for Business Services",
    "home.hero.subtitle": "A unified platform connecting SMEs with professional Sanad offices. Get your business licenses, permits, and registrations done faster.",
    "home.hero.myBookings": "My Bookings",
    "home.hero.browseServices": "Browse Services",
    "home.stats.avgRating": "Average Rating",
    "home.stats.servicesCompleted": "Services Completed",
    "home.stats.verifiedOffices": "Verified Offices",
    "home.title": "Everything You Need for Business Services",
    "home.subtitle": "A unified platform connecting SMEs with professional Sanad offices",
    "home.templates": "Document Templates",
    "home.templatesDesc": "Access thousands of business document templates",
    "home.browseTemplates": "Browse templates",
    "home.browseOffices": "Browse Offices",
    "home.offices": "Trusted Offices",
    "home.officesDesc": "Connect with certified Sanad offices across Oman",
    "office.exploreOffices": "Explore Offices",
    "office.notFound": "Office Not Found",
    "office.browseOffices": "Browse Offices",
    "office.backToOffices": "Back to Offices",
    "office.verified": "Verified",
    "office.website": "Website",
    "office.bookService": "Book Service",
    "office.about": "About",
    "office.services": "Services",
    "office.reviews": "Reviews",
    "office.aboutThisOffice": "About This Office",
    "office.location": "Location",
    "office.contactInformation": "Contact Information",
    "office.phone": "Phone",
    "office.email": "Email",
    "office.availableServices": "Available Services",
    "office.servicesDescription": "Professional business services offered by this office",
    "office.noServices": "No services listed yet",
    "office.anonymous": "Anonymous",
    "office.noReviews": "No reviews yet. Be the first to review!",
    "office.readyToBook": "Ready to book a service?",
    "office.selectServiceAndBook": "Select from our available services and schedule your appointment",
    "office.noServicesMatchFilters": "No services match your filters. Try adjusting your criteria.",
    "office.customQuote": "Custom Quote",
    "office.days": "days",
    
    // Booking Wizard
    "booking.selectService": "Select Service",
    "booking.chooseYourService": "Choose your service",
    "booking.requirements": "Requirements",
    "booking.provideDetails": "Provide details",
    "booking.dateTime": "Date & Time",
    "booking.pickSlot": "Pick a slot",
    "booking.review": "Review",
    "booking.confirmBooking": "Confirm booking",
    "booking.serviceSelected": "Service Selected",
    "booking.serviceMatchDescription": "Based on your preferences, this service is a great match!",
    "booking.bookingFailed": "Booking Failed",
    "booking.pleaseSelectService": "Please select a service",
    "booking.missingRequiredInfo": "Missing Required Information",
    "booking.pleaseFillIn": "Please fill in: {fields}",
    "booking.pleaseSelectDate": "Please select a date",
    "booking.pleaseSelectTimeSlot": "Please select a time slot",
    "booking.serviceBooking": "Service booking",
    
    // Templates Categories
    "templates.allTemplates": "All Templates",
    "templates.employment": "Employment",
    "templates.nocCertificates": "NOC Certificates",
    "templates.business": "Business",
    "templates.legal": "Legal",
    "templates.immigration": "Immigration",
    "templates.official": "Official",
    "templates.premium": "Premium",
    "templates.view": "View",
    "templates.previous": "Previous",
    "templates.next": "Next",
    "templates.page": "Page",
    "templates.noTemplatesFound": "No templates found",
    "templates.tryAdjustingFilters": "Try adjusting your search or filters",
    
    // Service Filters
    "services.filters": "Filters",
    "services.active": "Active",
    "services.clearFilters": "Clear Filters",
    "services.category": "Category",
    "services.selectCategory": "Select Category",
    "services.allCategories": "All Categories",
    "services.legal": "Legal",
    "services.business": "Business",
    "services.tax": "Tax",
    "services.registration": "Registration",
    "services.consultation": "Consultation",
    "services.priceRange": "Price Range",
    "services.resultsCount": "Showing {count} service(s)",
    "admin.contentTranslation": "Content Translation",
    "admin.contentTranslationDesc": "Manage Arabic translations for offices and templates",
    "admin.offices": "Offices",
    "admin.templates": "Templates",
    "admin.manageOfficeTranslations": "Manage Office Translations",
    "admin.manageOfficeTranslationsDesc": "Edit Arabic names and descriptions for Sanad offices",
    "admin.selectOffice": "Select an office",
    "admin.selectTemplate": "Select a template",
    "admin.selectTemplateFirst": "Please select a template first",
    "admin.templateNameArabic": "Template Name (Arabic)",
    "admin.templateDescriptionArabic": "Template Description (Arabic)",
    "admin.officeNameArabic": "Office Name (Arabic)",
    "admin.officeDescriptionArabic": "Office Description (Arabic)",
    "admin.enterArabicName": "Enter Arabic name",
    "admin.enterArabicDescription": "Enter Arabic description",
    "admin.translationUpdated": "Translation updated successfully",
    "admin.translationError": "Failed to update translation",
    "admin.translationUpdateFailed": "Failed to update translation",
    "admin.selectOfficeFirst": "Please select an office first",
    "admin.manageTemplateTranslations": "Manage Template Translations",
    "admin.manageTemplateTranslationsDesc": "Edit Arabic names and descriptions for document templates",
    "admin.templateTranslationsComingSoon": "Template translations management coming soon",
    "admin.bulkImport": "Bulk Import",
    "admin.bulkImportDesc": "Import multiple translations at once using CSV or Excel files",
    "admin.downloadTemplate": "Download Template",
    "admin.uploadFile": "Upload File",
    "admin.importTranslations": "Import Translations",
    "admin.importSuccess": "Successfully imported {count} translations",
    "admin.importError": "Failed to import translations",
    "admin.selectFile": "Select CSV or Excel file",
    "admin.fileFormat": "File format: CSV or Excel (.xlsx)",
    "admin.templateColumns": "Required columns: id, nameAr, descriptionAr",
    "admin.processing": "Processing...",
    "admin.translationQuality": "Translation Quality",
    "admin.complete": "Complete",
    "admin.partial": "Partial",
    "admin.missing": "Missing",
    "admin.completionStatus": "Completion Status",
    "admin.suggestions": "Suggestions",
    "common.saving": "Saving...",
    "home.government": "Government Integrated",
    "home.governmentDesc": "Direct integration with MOCIP, MOL, and ROP for seamless verification and compliance",
    "home.booking": "Book Services",
    "home.bookingDesc": "Schedule appointments online across all regions",
    "home.bookService": "Book a service",
    "home.trusted": "Trusted by SMEs",
    "home.trustedDesc": "Join thousands of Omani businesses using SmartPro for their business service needs",
    "home.fast": "Fast & Efficient",
    "home.fastDesc": "Reduce processing time from weeks to days with automated workflows and digital processes",
    "home.cta": "Ready to Transform Your Business Services?",
    "home.ctaDesc": "Join SmartPro today and experience the future of business services in Oman",
    "home.learnMore": "Learn More",
    "home.getStarted": "Get Started",
    "home.viewTemplates": "View Templates",
    "home.exploreOffices": "Explore Offices",
    "home.features.offices": "Trusted Sanad Offices",
    "home.features.officesDesc": "Connect with certified business service offices across Oman",
    "home.features.templates": "Document Templates",
    "home.features.templatesDesc": "Access thousands of ready-to-use business document templates",
    "home.features.booking": "Online Booking",
    "home.features.bookingDesc": "Schedule appointments and manage bookings seamlessly",
    
    // Offices Page (Additional Keys)
    "offices.registerYourOffice": "Register Your Office",
    "offices.professionalServices": "Professional business services",
    "offices.reviewsCount": "reviews",
    "offices.verified": "Verified",
    "offices.instantBooking": "Instant Booking",
    "offices.viewOffice": "View Office",
    "offices.previous": "Previous",
    "offices.next": "Next",
    "offices.page": "Page",
    "offices.noOfficesFound": "No offices found",
    "offices.adjustSearchCriteria": "Try adjusting your search criteria",
    "offices.beFirstToRegister": "Be the first to register your Sanad office",
    
    // Feature Cards Section
    "home.featureCards.sectionBadge": "Platform Features",
    "home.featureCards.sectionTitle": "Why Choose SmartPro?",
    "home.featureCards.sectionSubtitle": "Everything you need to manage business services in one place",
    "home.featureCards.verifiedOffices": "Verified Sanad Offices",
    "home.featureCards.verifiedOfficesDesc": "Browse hundreds of verified professional offices with transparent pricing and reviews",
    "home.featureCards.exploreOffices": "Explore Offices",
    "home.featureCards.marketplace": "Service Marketplace",
    "home.featureCards.marketplaceDesc": "Post service requests and receive competitive bids from multiple offices",
    "home.featureCards.browseMarketplace": "Browse Marketplace",
    "home.featureCards.documentTemplates": "Document Templates",
    "home.featureCards.documentTemplatesDesc": "Access ready-to-use templates for contracts, applications, and business documents",
    "home.featureCards.viewTemplates": "View Templates",
    "home.featureCards.easyBooking": "Easy Booking",
    "home.featureCards.easyBookingDesc": "Schedule appointments, track progress, and manage all your bookings in one dashboard",
    "home.featureCards.myBookings": "My Bookings",
    "home.featureCards.realtimeChat": "Real-time Chat",
    "home.featureCards.realtimeChatDesc": "Communicate directly with offices, get instant updates, and resolve queries quickly",
    "home.featureCards.openChat": "Open Chat",
    "home.featureCards.loyaltyRewards": "Loyalty Rewards",
    "home.featureCards.loyaltyRewardsDesc": "Earn points with every booking and redeem them for discounts on future services",
    "home.featureCards.viewRewards": "View Rewards",
    
    // Common
    "common.signIn": "Sign In",
    "common.signOut": "Sign Out",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.select": "Select",
    "common.all": "All",
    "common.none": "None",
    "common.apply": "Apply",
    "common.reset": "Reset",
    "common.clear": "Clear",
    "common.connected": "Connected",
    "common.offline": "Offline",
    
    // Offices
    "offices.title": "Sanad Offices",
    "offices.subtitle": "Find certified business service offices across Oman",
    "offices.searchPlaceholder": "Search by name or location...",
    "offices.filterByRegion": "Filter by Region",
    "offices.filterByService": "Filter by Service",
    "offices.allRegions": "All Regions",
    "offices.allServices": "All Services",
    "offices.noResults": "No offices found matching your criteria",
    "offices.viewProfile": "View Profile",
    "offices.bookNow": "Book Now",
    "offices.rating": "Rating",
    "offices.reviews": "Reviews",
    "offices.services": "Services",
    "offices.location": "Location",
    "offices.contact": "Contact",
    "offices.about": "About",
    "offices.workingHours": "Working Hours",
    "offices.closed": "Closed",
    "offices.highestRated": "Highest Rated",
    "offices.mostReviews": "Most Reviews",
    "offices.nameAZ": "Name (A-Z)",
    "offices.showing": "Showing",
    "offices.of": "of",
    "offices.offices": "offices",
    
    // Templates
    "templates.title": "Document Templates",
    "templates.subtitle": "Access thousands of business document templates",
    "templates.searchPlaceholder": "Search templates...",
    "templates.category": "Category",
    "templates.allCategories": "All Categories",
    "templates.language": "Language",
    "templates.useTemplate": "Use Template",
    "templates.preview": "Preview",
    "templates.download": "Download",
    "templates.fillForm": "Fill Form",
    "templates.generate": "Generate Document",
    "templates.generating": "Generating...",
    "templates.noResults": "No templates found",
    
    // Bookings
    "bookings.title": "My Bookings",
    "bookings.upcoming": "Upcoming",
    "bookings.past": "Past",
    "bookings.cancelled": "Cancelled",
    "bookings.noBookings": "No bookings found",
    "bookings.listView": "List View",
    "bookings.calendarView": "Calendar View",
    "bookings.history": "Booking History",
    "bookings.historyDesc": "View and manage your service bookings",
    "bookings.bookingDate": "Booking Date",
    "bookings.service": "Service",
    "bookings.office": "Office",
    "bookings.status": "Status",
    "bookings.actions": "Actions",
    "bookings.cancel": "Cancel Booking",
    "bookings.reschedule": "Reschedule",
    "bookings.viewDetails": "View Details",
    "bookings.confirmCancel": "Are you sure you want to cancel this booking?",
    "bookings.selectDate": "Select Date",
    "bookings.selectTime": "Select Time",
    "bookings.confirmBooking": "Confirm Booking",
    
    // Booking flow
    "booking.title": "Book a Service",
    "booking.backToOffice": "Back to Office",
    "booking.selectDate": "Select Date",
    "booking.selectDateDesc": "Choose your preferred appointment date",
    "booking.selectTime": "Select Time",
    "booking.availableSlots": "Available time slots for",
    
    // Loyalty
    "loyalty.title": "Loyalty Rewards",
    "loyalty.subtitle": "Earn points and get exclusive rewards",
    "loyalty.availablePoints": "Available Points",
    
    // Referral
    "referral.title": "Refer Friends",
    
    // Admin
    "admin.exportSuccess": "Export completed successfully",
    "admin.exportError": "Failed to export",
    "admin.exportAll": "Export All Translations",
    
    // Notifications
    "notifications.title": "Notification Preferences",
    "notifications.subtitle": "Manage how you receive notifications",
    "notifications.channels": "Notification Channels",
    "notifications.channelsDesc": "Choose how you want to receive notifications",
    "notifications.email": "Email Notifications",
    "notifications.emailDesc": "Receive notifications via email",
    "notifications.sms": "SMS Notifications",
    "notifications.smsDesc": "Receive notifications via SMS",
    "notifications.types": "Notification Types",
    "notifications.typesDesc": "Choose which types of notifications you want to receive",
    "notifications.confirmations": "Booking Confirmations",
    "notifications.confirmationsDesc": "Get notified when bookings are confirmed or updated",
    "notifications.reminders": "Reminders",
    "notifications.remindersDesc": "Receive reminders about upcoming appointments",
    "notifications.marketing": "Marketing & Updates",
    "notifications.marketingDesc": "Get news about new features and special offers",
    
    // Settings
    "settings.languageSettings": "Language Settings",
    "settings.languageSettingsDesc": "Choose your preferred language for the platform interface",
    "settings.preferredLanguage": "Preferred Language",
    "settings.preferredLanguageDesc": "Select your preferred language for the interface",
    "settings.selectLanguage": "Select Language",
    "settings.languageUpdated": "Language preference updated successfully",
    "settings.languageUpdateFailed": "Failed to update language preference",
    "settings.languageInfo": "About Language Settings",
    "settings.languageInfoPoint1": "Your language preference will be saved to your account",
    "settings.languageInfoPoint2": "The interface will update immediately after saving",
    "settings.languageInfoPoint3": "This setting will sync across all your devices",
    
    // Profile
    "profile.title": "My Profile",
    "profile.personalInfo": "Personal Information",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.language": "Preferred Language",
    "profile.updateProfile": "Update Profile",
    "profile.changePassword": "Change Password",
    "profile.updateSuccess": "Profile updated successfully",
    "profile.updateError": "Failed to update profile",
    "profile.nameRequired": "Name is required",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm Password",
    
    // Validation
    "validation.required": "This field is required",
    "validation.email": "Please enter a valid email address",
    "validation.phone": "Please enter a valid phone number",
    "validation.minLength": "Minimum length is {min} characters",
    "validation.maxLength": "Maximum length is {max} characters",
    "validation.passwordMatch": "Passwords do not match",
    
    // Messages
    "message.success": "Operation completed successfully",
    "message.error": "An error occurred. Please try again",
    "message.saveSuccess": "Saved successfully",
    "message.deleteSuccess": "Deleted successfully",
    "message.updateSuccess": "Updated successfully",
    "message.createSuccess": "Created successfully",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.sanadOffices": "مكاتب سند",
    "nav.documentTemplates": "قوالب المستندات",
    "nav.myBookings": "حجوزاتي",
    "nav.myOffices": "مكاتبي",
    "nav.ownerDashboard": "لوحة التحكم",
    "nav.chatInbox": "صندوق الدردشة",
    "nav.chatAnalytics": "تحليلات الدردشة",
    "nav.cannedResponses": "الردود الجاهزة",
    "nav.staffManagement": "إدارة الموظفين",
    "nav.staffPerformance": "أداء الموظفين",
    "nav.followUpSettings": "إعدادات المتابعة",
    "nav.loyaltyRewards": "مكافآت الولاء",
    "nav.referFriends": "إحالة الأصدقاء",
    "nav.analytics": "التحليلات",
    "nav.userProfile": "الملف الشخصي",
    "nav.contentTranslation": "ترجمة المحتوى",
    "nav.notificationPreferences": "تفضيلات الإشعارات",
    "nav.adminDashboard": "لوحة تحكم المسؤول",
    "nav.adminAnalytics": "تحليلات المسؤول",
    "nav.marketplace": "تصفح السوق",
    "nav.profile": "الملف الشخصي",
    "nav.logout": "تسجيل الخروج",
    "nav.myServiceRequests": "طلبات الخدمة",
    "nav.browseMarketplace": "تصفح السوق",
    "nav.officeAnalytics": "تحليلات المكتب",
    "nav.userManagement": "إدارة المستخدمين",
    "nav.officeVerification": "التحقق من المكاتب",
    "nav.translationRequests": "طلبات الترجمة",
    "nav.translationAnalytics": "تحليلات الترجمة",
    "nav.translationQuality": "جودة الترجمة",
    "nav.reviewQueue": "قائمة المراجعة",
    "nav.batchProcessing": "المعالجة الدفعية",
    "nav.translatorTraining": "تدريب المترجمين",
    
    // Home page
    "home.hero.title": "كل ما تحتاجه لخدمات الأعمال",
    "home.hero.subtitle": "منصة موحدة تربط الشركات الصغيرة والمتوسطة بمكاتب سند المهنية. احصل على تراخيص عملك وتصاريحك وتسجيلاتك بشكل أسرع.",
    "home.hero.myBookings": "حجوزاتي",
    "home.hero.browseServices": "تصفح الخدمات",
    "home.stats.avgRating": "متوسط التقييم",
    "home.stats.servicesCompleted": "الخدمات المكتملة",
    "home.stats.verifiedOffices": "المكاتب الموثقة",
    "home.title": "كل ما تحتاجه لخدمات الأعمال",
    "home.subtitle": "منصة موحدة تربط الشركات الصغيرة والمتوسطة بمكاتب سند المهنية",
    "home.templates": "قوالب المستندات",
    "home.templatesDesc": "احصل على آلاف القوالب التجارية",
    "home.browseTemplates": "تصفح القوالب",
    "home.browseOffices": "تصفح المكاتب",
    "home.offices": "مكاتب معتمدة",
    "home.officesDesc": "تواصل مع مكاتب سند الموثوقة",
    "office.exploreOffices": "استكشف المكاتب",
    "office.notFound": "لم يتم العثور على المكتب",
    "office.browseOffices": "تصفح المكاتب",
    "office.backToOffices": "العودة إلى المكاتب",
    "office.verified": "موثق",
    "office.website": "الموقع الإلكتروني",
    "office.bookService": "احجز خدمة",
    "office.about": "حول",
    "office.services": "الخدمات",
    "office.reviews": "التقييمات",
    "office.aboutThisOffice": "حول هذا المكتب",
    "office.location": "الموقع",
    "office.contactInformation": "معلومات الاتصال",
    "office.phone": "الهاتف",
    "office.email": "البريد الإلكتروني",
    "office.availableServices": "الخدمات المتاحة",
    "office.servicesDescription": "خدمات الأعمال المهنية التي يقدمها هذا المكتب",
    "office.noServices": "لم يتم إدراج أي خدمات بعد",
    "office.anonymous": "مجهول",
    "office.noReviews": "لا توجد تقييمات بعد. كن أول من يقيم!",
    "office.readyToBook": "هل أنت مستعد لحجز خدمة؟",
    "office.selectServiceAndBook": "اختر من خدماتنا المتاحة وحدد موعدك",
    "office.noServicesMatchFilters": "لا توجد خدمات تطابق الفلاتر. حاول تعديل معاييرك.",
    "office.customQuote": "عرض سعر مخصص",
    "office.days": "أيام",
    
    // Booking Wizard
    "booking.selectService": "اختر الخدمة",
    "booking.chooseYourService": "اختر خدمتك",
    "booking.requirements": "المتطلبات",
    "booking.provideDetails": "قدم التفاصيل",
    "booking.dateTime": "التاريخ والوقت",
    "booking.pickSlot": "اختر موعدًا",
    "booking.review": "مراجعة",
    "booking.confirmBooking": "تأكيد الحجز",
    "booking.serviceSelected": "تم اختيار الخدمة",
    "booking.serviceMatchDescription": "بناءً على تفضيلاتك، هذه الخدمة مناسبة جدًا!",
    "booking.bookingFailed": "فشل الحجز",
    "booking.pleaseSelectService": "يرجى اختيار خدمة",
    "booking.missingRequiredInfo": "معلومات مطلوبة ناقصة",
    "booking.pleaseFillIn": "يرجى ملء: {fields}",
    "booking.pleaseSelectDate": "يرجى اختيار تاريخ",
    "booking.pleaseSelectTimeSlot": "يرجى اختيار موعد",
    "booking.serviceBooking": "حجز خدمة",
    
    // Templates Categories
    "templates.allTemplates": "جميع القوالب",
    "templates.employment": "التوظيف",
    "templates.nocCertificates": "شهادات عدم الممانعة",
    "templates.business": "الأعمال",
    "templates.legal": "قانوني",
    "templates.immigration": "الهجرة",
    "templates.official": "رسمي",
    "templates.premium": "مميز",
    "templates.view": "عرض",
    "templates.previous": "السابق",
    "templates.next": "التالي",
    "templates.page": "صفحة",
    "templates.noTemplatesFound": "لم يتم العثور على قوالب",
    "templates.tryAdjustingFilters": "حاول تعديل البحث أو الفلاتر",
    
    // Service Filters
    "services.filters": "الفلاتر",
    "services.active": "نشط",
    "services.clearFilters": "مسح الفلاتر",
    "services.category": "الفئة",
    "services.selectCategory": "اختر الفئة",
    "services.allCategories": "جميع الفئات",
    "services.legal": "قانوني",
    "services.business": "أعمال",
    "services.tax": "ضرائب",
    "services.registration": "تسجيل",
    "services.consultation": "استشارة",
    "services.priceRange": "نطاق السعر",
    "services.resultsCount": "عرض {count} خدمة",
    "admin.contentTranslation": "ترجمة المحتوى",
    "admin.contentTranslationDesc": "إدارة الترجمات العربية للمكاتب والقوالب",
    "admin.offices": "المكاتب",
    "admin.templates": "القوالب",
    "admin.manageOfficeTranslations": "إدارة ترجمات المكاتب",
    "admin.manageOfficeTranslationsDesc": "تحرير الأسماء والأوصاف العربية لمكاتب سند",
    "admin.selectOffice": "اختر مكتب",
    "admin.selectTemplate": "اختر قالب",
    "admin.selectTemplateFirst": "الرجاء اختيار قالب أولاً",
    "admin.templateNameArabic": "اسم القالب (عربي)",
    "admin.templateDescriptionArabic": "وصف القالب (عربي)",
    "admin.officeNameArabic": "اسم المكتب (عربي)",
    "admin.officeDescriptionArabic": "وصف المكتب (عربي)",
    "admin.enterArabicName": "أدخل الاسم بالعربي",
    "admin.enterArabicDescription": "أدخل الوصف بالعربي",
    "admin.translationUpdated": "تم تحديث الترجمة بنجاح",
    "admin.translationError": "فشل تحديث الترجمة",
    "admin.translationUpdateFailed": "فشل تحديث الترجمة",
    "admin.selectOfficeFirst": "الرجاء اختيار مكتب أولاً",
    "admin.manageTemplateTranslations": "إدارة ترجمات القوالب",
    "admin.manageTemplateTranslationsDesc": "تحرير الأسماء والأوصاف العربية لقوالب المستندات",
    "admin.templateTranslationsComingSoon": "إدارة ترجمات القوالب قريباً",
    "admin.bulkImport": "استيراد جماعي",
    "admin.bulkImportDesc": "استيراد عدة ترجمات دفعة واحدة باستخدام ملفات CSV أو Excel",
    "admin.downloadTemplate": "تحميل النموذج",
    "admin.uploadFile": "رفع الملف",
    "admin.importTranslations": "استيراد الترجمات",
    "admin.importSuccess": "تم استيراد {count} ترجمة بنجاح",
    "admin.importError": "فشل استيراد الترجمات",
    "admin.selectFile": "اختر ملف CSV أو Excel",
    "admin.fileFormat": "صيغة الملف: CSV أو Excel (.xlsx)",
    "admin.templateColumns": "الأعمدة المطلوبة: id, nameAr, descriptionAr",
    "admin.processing": "جاري المعالجة...",
    "admin.translationQuality": "جودة الترجمة",
    "admin.complete": "كامل",
    "admin.partial": "جزئي",
    "admin.missing": "مفقود",
    "admin.completionStatus": "حالة الإكمال",
    "admin.suggestions": "اقتراحات",
    "common.saving": "جاري الحفظ...",
    "common.connected": "متصل",
    "common.offline": "غير متصل",
    "home.government": "متكامل حكوميًا",
    "home.governmentDesc": "تكامل مباشر مع وزارة التجارة والصناعة ووزارة العمل وشرطة عمان للتحقق السلس والامتثال",
    "home.booking": "حجز خدمة",
    "home.bookingDesc": "حدد المواعيد عبر الإنترنت في جميع المناطق",
    "home.bookService": "احجز خدمة",
    "home.trusted": "موثوق من قبل الشركات",
    "home.trustedDesc": "انضم إلى آلاف الشركات العمانية التي تستخدم SmartPro لاحتياجات خدمات أعمالها",
    "home.fast": "سريع وفعال",
    "home.fastDesc": "قلل وقت المعالجة من أسابيع إلى أيام باستخدام سير العمل الآلي والعمليات الرقمية",
    "home.cta": "هل أنت مستعد لتحويل خدمات عملك؟",
    "home.ctaDesc": "انضم إلى SmartPro اليوم واختبر مستقبل خدمات الأعمال في عمان",
    "home.learnMore": "اعرف المزيد",
    "home.getStarted": "ابدأ الآن",
    "home.viewTemplates": "عرض القوالب",
    "home.exploreOffices": "استكشف المكاتب",
    "home.features.offices": "مكاتب سند موثوقة",
    "home.features.officesDesc": "تواصل مع مكاتب الخدمات التجارية المعتمدة في جميع أنحاء عمان",
    "home.features.templates": "قوالب المستندات",
    "home.features.templatesDesc": "احصل على آلاف القوالب التجارية الجاهزة للاستخدام",
    "home.features.booking": "الحجز عبر الإنترنت",
    "home.features.bookingDesc": "جدولة المواعيد وإدارة الحجوزات بسهولة",
    
    // Offices Page (Additional Keys)
    "offices.registerYourOffice": "سجل مكتبك",
    "offices.professionalServices": "خدمات أعمال محترفة",
    "offices.reviewsCount": "تقييم",
    "offices.verified": "موثق",
    "offices.instantBooking": "حجز فوري",
    "offices.viewOffice": "عرض المكتب",
    "offices.previous": "السابق",
    "offices.next": "التالي",
    "offices.page": "صفحة",
    "offices.noOfficesFound": "لم يتم العثور على مكاتب",
    "offices.adjustSearchCriteria": "حاول تعديل معايير البحث",
    "offices.beFirstToRegister": "كن أول من يسجل مكتب سند",
    
    // Feature Cards Section
    "home.featureCards.sectionBadge": "ميزات المنصة",
    "home.featureCards.sectionTitle": "لماذا تختار SmartPro؟",
    "home.featureCards.sectionSubtitle": "كل ما تحتاجه لإدارة خدمات الأعمال في مكان واحد",
    "home.featureCards.verifiedOffices": "مكاتب سند موثقة",
    "home.featureCards.verifiedOfficesDesc": "تصفح مئات المكاتب المهنية الموثقة مع أسعار شفافة وتقييمات",
    "home.featureCards.exploreOffices": "استكشف المكاتب",
    "home.featureCards.marketplace": "سوق الخدمات",
    "home.featureCards.marketplaceDesc": "انشر طلبات الخدمة واستقبل عروضًا تنافسية من مكاتب متعددة",
    "home.featureCards.browseMarketplace": "تصفح السوق",
    "home.featureCards.documentTemplates": "قوالب المستندات",
    "home.featureCards.documentTemplatesDesc": "احصل على قوالب جاهزة للاستخدام للعقود والطلبات ومستندات الأعمال",
    "home.featureCards.viewTemplates": "عرض القوالب",
    "home.featureCards.easyBooking": "حجز سهل",
    "home.featureCards.easyBookingDesc": "جدول المواعيد وتتبع التقدم وأدر جميع حجوزاتك في لوحة واحدة",
    "home.featureCards.myBookings": "حجوزاتي",
    "home.featureCards.realtimeChat": "دردشة فورية",
    "home.featureCards.realtimeChatDesc": "تواصل مباشرة مع المكاتب واحصل على تحديثات فورية وحل الاستفسارات بسرعة",
    "home.featureCards.openChat": "فتح الدردشة",
    "home.featureCards.loyaltyRewards": "مكافآت الولاء",
    "home.featureCards.loyaltyRewardsDesc": "اكسب نقاطًا مع كل حجز واستبدلها بخصومات على الخدمات المستقبلية",
    "home.featureCards.viewRewards": "عرض المكافآت",
    
    // Common
    "common.signIn": "تسجيل الدخول",
    "common.signOut": "تسجيل الخروج",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.view": "عرض",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.submit": "إرسال",
    "common.close": "إغلاق",
    "common.confirm": "تأكيد",
    "common.download": "تحميل",
    "common.upload": "رفع",
    "common.select": "اختيار",
    "common.all": "الكل",
    "common.none": "لا شيء",
    "common.apply": "تطبيق",
    "common.reset": "إعادة تعيين",
    "common.clear": "مسح",
    
    // Offices
    "offices.title": "مكاتب سند",
    "offices.subtitle": "اعثر على مكاتب خدمات الأعمال المعتمدة في جميع أنحاء عمان",
    "offices.searchPlaceholder": "البحث بالاسم أو الموقع...",
    "offices.filterByRegion": "تصفية حسب المنطقة",
    "offices.filterByService": "تصفية حسب الخدمة",
    "offices.allRegions": "جميع المناطق",
    "offices.allServices": "جميع الخدمات",
    "offices.noResults": "لم يتم العثور على مكاتب تطابق معاييرك",
    "offices.viewProfile": "عرض الملف الشخصي",
    "offices.bookNow": "احجز الآن",
    "offices.rating": "التقييم",
    "offices.reviews": "المراجعات",
    "offices.services": "الخدمات",
    "offices.location": "الموقع",
    "offices.contact": "الاتصال",
    "offices.about": "عن المكتب",
    "offices.workingHours": "ساعات العمل",
    "offices.closed": "مغلق",
    "offices.highestRated": "الأعلى تقييماً",
    "offices.mostReviews": "الأكثر مراجعات",
    "offices.nameAZ": "الاسم (أ-ي)",
    "offices.showing": "عرض",
    "offices.of": "من",
    "offices.offices": "مكاتب",
    
    // Templates
    "templates.title": "قوالب المستندات",
    "templates.subtitle": "احصل على آلاف قوالب مستندات الأعمال",
    "templates.searchPlaceholder": "البحث عن القوالب...",
    "templates.category": "الفئة",
    "templates.allCategories": "جميع الفئات",
    "templates.language": "اللغة",
    "templates.useTemplate": "استخدم القالب",
    "templates.preview": "معاينة",
    "templates.download": "تحميل",
    "templates.fillForm": "ملء النموذج",
    "templates.generate": "إنشاء المستند",
    "templates.generating": "جاري الإنشاء...",
    "templates.noResults": "لم يتم العثور على قوالب",
    
    // Bookings
    "bookings.title": "حجوزاتي",
    "bookings.upcoming": "القادمة",
    "bookings.past": "السابقة",
    "bookings.cancelled": "الملغاة",
    "bookings.noBookings": "لا توجد حجوزات",
    "bookings.listView": "عرض القائمة",
    "bookings.calendarView": "عرض التقويم",
    "bookings.history": "سجل الحجوزات",
    "bookings.historyDesc": "عرض وإدارة حجوزات الخدمات",
    "bookings.bookingDate": "تاريخ الحجز",
    "bookings.service": "الخدمة",
    "bookings.office": "المكتب",
    "bookings.status": "الحالة",
    "bookings.actions": "الإجراءات",
    "bookings.cancel": "إلغاء الحجز",
    "bookings.reschedule": "إعادة الجدولة",
    "bookings.viewDetails": "عرض التفاصيل",
    "bookings.confirmCancel": "هل أنت متأكد من إلغاء هذا الحجز؟",
    "bookings.selectDate": "اختر التاريخ",
    "bookings.selectTime": "اختر الوقت",
    "bookings.confirmBooking": "تأكيد الحجز",
    
    // Booking flow
    "booking.title": "احجز خدمة",
    "booking.backToOffice": "العودة إلى المكتب",
    "booking.selectDate": "اختر التاريخ",
    "booking.selectDateDesc": "اختر تاريخ الموعد المفضل لديك",
    "booking.selectTime": "اختر الوقت",
    "booking.availableSlots": "الأوقات المتاحة لـ",
    
    // Loyalty
    "loyalty.title": "مكافآت الولاء",
    "loyalty.subtitle": "اكسب النقاط واحصل على مكافآت حصرية",
    "loyalty.availablePoints": "النقاط المتاحة",
    
    // Referral
    "referral.title": "إحالة الأصدقاء",
    
    // Admin
    "admin.exportSuccess": "تم التصدير بنجاح",
    "admin.exportError": "فشل التصدير",
    "admin.exportAll": "تصدير جميع الترجمات",
        // Notifications
    "notifications.title": "تفضيلات الإشعارات",
    "notifications.subtitle": "إدارة كيفية تلقي الإشعارات",
    "notifications.channels": "قنوات الإشعارات",
    "notifications.channelsDesc": "اختر كيف تريد تلقي الإشعارات",
    "notifications.email": "إشعارات البريد الإلكتروني",
    "notifications.emailDesc": "تلقي الإشعارات عبر البريد الإلكتروني",
    "notifications.sms": "إشعارات الرسائل النصية",
    "notifications.smsDesc": "تلقي الإشعارات عبر الرسائل النصية",
    "notifications.types": "أنواع الإشعارات",
    "notifications.typesDesc": "اختر أنواع الإشعارات التي تريد تلقيها",
    "notifications.confirmations": "تأكيدات الحجز",
    "notifications.confirmationsDesc": "احصل على إشعار عند تأكيد أو تحديث الحجوزات",
    "notifications.reminders": "التذكيرات",
    "notifications.remindersDesc": "تلقي تذكيرات حول المواعيد القادمة",
    "notifications.marketing": "التسويق والتحديثات",
    "notifications.marketingDesc": "احصل على أخبار حول الميزات الجديدة والعروض الخاصة",
    
    // Settings
    "settings.languageSettings": "إعدادات اللغة",
    "settings.languageSettingsDesc": "اختر لغتك المفضلة لواجهة المنصة",
    "settings.preferredLanguage": "اللغة المفضلة",
    "settings.preferredLanguageDesc": "اختر لغتك المفضلة للواجهة",
    "settings.selectLanguage": "اختر اللغة",
    "settings.languageUpdated": "تم تحديث تفضيل اللغة بنجاح",
    "settings.languageUpdateFailed": "فشل تحديث تفضيل اللغة",
    "settings.languageInfo": "حول إعدادات اللغة",
    "settings.languageInfoPoint1": "سيتم حفظ تفضيل اللغة في حسابك",
    "settings.languageInfoPoint2": "سيتم تحديث الواجهة فورًا بعد الحفظ",
    "settings.languageInfoPoint3": "سيتم مزامنة هذا الإعداد عبر جميع أجهزتك",
    
    // Profile
    "profile.title": "الملف الشخصي",
    "profile.personalInfo": "المعلومات الشخصية",
    "profile.name": "الاسم",
    "profile.email": "البريد الإلكتروني",
    "profile.phone": "رقم الهاتف",
    "profile.language": "اللغة المفضلة",
    "profile.updateProfile": "تحديث الملف الشخصي",
    "profile.changePassword": "تغيير كلمة المرور",
    "profile.updateSuccess": "تم تحديث الملف الشخصي بنجاح",
    "profile.updateError": "فشل تحديث الملف الشخصي",
    "profile.nameRequired": "الاسم مطلوب",
    "profile.currentPassword": "كلمة المرور الحالية",
    "profile.newPassword": "كلمة المرور الجديدة",
    "profile.confirmPassword": "تأكيد كلمة المرور",
    
    // Validation
    "validation.required": "هذا الحقل مطلوب",
    "validation.email": "يرجى إدخال عنوان بريد إلكتروني صحيح",
    "validation.phone": "يرجى إدخال رقم هاتف صحيح",
    "validation.minLength": "الحد الأدنى للطول هو {min} أحرف",
    "validation.maxLength": "الحد الأقصى للطول هو {max} أحرف",
    "validation.passwordMatch": "كلمات المرور غير متطابقة",
    
    // Messages
    "message.success": "تمت العملية بنجاح",
    "message.error": "حدث خطأ. يرجى المحاولة مرة أخرى",
    "message.saveSuccess": "تم الحفظ بنجاح",
    "message.deleteSuccess": "تم الحذف بنجاح",
    "message.updateSuccess": "تم التحديث بنجاح",
    "message.createSuccess": "تم الإنشاء بنجاح",
  },
};

// Helper function to detect browser language
function detectBrowserLanguage(): Language {
  const browserLang = navigator.language || navigator.languages?.[0];
  // Check if browser language is Arabic (ar, ar-*)
  if (browserLang?.toLowerCase().startsWith('ar')) {
    return 'ar';
  }
  // Default to English for all other languages
  return 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>(() => {
    // Priority: localStorage > browser language > default (en)
    const saved = localStorage.getItem("smartpro-language");
    if (saved === "ar" || saved === "en") {
      return saved;
    }
    // First visit: detect from browser
    const detected = detectBrowserLanguage();
    localStorage.setItem("smartpro-language", detected);
    return detected;
  });

  const updateLanguageMutation = trpc.auth.updateLanguagePreference.useMutation();

  // Sync with user's preferred language from database
  useEffect(() => {
    if (user?.preferredLanguage && (user.preferredLanguage === "ar" || user.preferredLanguage === "en")) {
      setLanguageState(user.preferredLanguage);
      localStorage.setItem("smartpro-language", user.preferredLanguage);
    }
  }, [user]);

  useEffect(() => {
    // Save to localStorage whenever language changes
    localStorage.setItem("smartpro-language", language);
    
    // Update document direction and lang attribute
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Update database if user is logged in
    if (user) {
      updateLanguageMutation.mutate({ language: lang });
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
